name: FrozorGames
description: Game Engine
author: Artix
version: 1.0.0
main: frozor.game.CastleSiege.CastleSiege
commands:
  kit:
    description: Shows current kit or changes your kit
    usage: /kit
  game:
    description: Changes game stuff
    usage: /game
